# Generated by Django 5.2.4 on 2025-07-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=100, verbose_name='Passenger Name')),
                ('user_phone_number', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('train_no', models.CharField(max_length=10, verbose_name='Train Number')),
                ('train_name', models.CharField(max_length=100, verbose_name='Train Name')),
                ('start_date_of_journey', models.DateField(verbose_name='Journey Start Date')),
                ('coach', models.CharField(blank=True, max_length=10, verbose_name='Coach Number')),
                ('berth', models.CharField(blank=True, max_length=10, verbose_name='Berth Number')),
                ('pnr', models.CharField(blank=True, max_length=20, verbose_name='PNR Number')),
                ('description', models.TextField(verbose_name='Complaint Description')),
                ('train_depo', models.CharField(max_length=100, verbose_name='Train Depot')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Passenger Complaint',
                'verbose_name_plural': 'Passenger Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
